name: lint

# on events
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
    codespell-pr:
      name: codespell-pr
      runs-on: ubuntu-latest
      steps:
        - name: Checkout current repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 2  # current PR merge commit + 1 back

        - name: codespell
          uses: codespell-project/actions-codespell@v2
          with:
            check_filenames: true
            reporter: github-pr-review

    shellcheck-pr:
      name: shellcheck-pr
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: circleci/shellcheck@3.1.2
          with:
            reporter: github-pr-review
